"""a

Revision ID: 94303af4f51e
Revises: 19ba0b5d9ed3
Create Date: 2023-04-16 12:40:30.848664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94303af4f51e'
down_revision = '19ba0b5d9ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sigf_challenge_sub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writeup', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sigf_challenge_sub', schema=None) as batch_op:
        batch_op.drop_column('writeup')

    # ### end Alembic commands ###
